---
title: Homelab
favicon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/homepage.png
headerStyle: clean
layout:
  Applications:
    style: row
    columns: 3
  Monitoring:
    style: row
    columns: 3
  Media:
    style: row
    columns: 4
  Tools:
    style: row
    columns: 2
  Developer:
    style: row
    columns: 2
