---
title: Homelab
favicon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/homepage.png
headerStyle: clean
layout:
  Management:
    style: row
    columns: 1
  Applications:
    style: row
    columns: 5
  Media:
    style: row
    columns: 4
  Network:
    style: row
    columns: 1
  Developer:
    style: row
    columns: 2
