{
 "title": "Internet connection",
 "tags": [
  "speedtest",
  "ping"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Download",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Speedtest Ping",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds"
    }
   ]
  },
  {
   "title": "Internet Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg_over_time((max(probe_success{routing=\"external\"}) == bool 0)[$__range:30s])) * 100"
    }
   ]
  },
  {
   "title": "Speedtest Graph",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_bits_per_second{}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "probe_success{job=\"ping\"}",
     "legendFormat": "{{humanname}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(humanname) (probe_icmp_duration_seconds{routing=\"external\"})",
     "legendFormat": "{{humanname}}"
    },
    {
     "expr": "sum by(humanname) (probe_icmp_duration_seconds{routing=\"local\"})",
     "legendFormat": "{{humanname}}"
    }
   ]
  }
 ]
}